dependencies:
  - name: mongodb
    version: "0.4.17"
    repository: "https://kubernetes-charts.storage.googleapis.com/"
  - name: postgresql
    version: "0.7.1"
    repository: "https://kubernetes-charts.storage.googleapis.com/"
    condition: postgresql.enabled
