# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
application:
  track: stable
  tier: web
service:
  enabled: true
  name: web
  type: ClusterIP
  url: http://my.host.com/
  externalPort: 8080
  internalPort: 8080
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
mongodb:
  image:
    tag: 3.6
  usePassword: false
  mongodbExtraFlags:
   - "--wiredTigerCacheSizeGB=0.25"
  resources:
    requests:
      memory: 512Mi
