version: '3'
services:
  mongodb:
    image: mongo
    volumes:
     - ./mongo/data:/data/db
  server:
    image: openjdk
    ports:
     - "8080:8080"
     - "9999:9999"
    volumes:
     - ./target/:/server/
    command: java -Xdebug -Xrunjdwp:transport=dt_socket,address=9999,server=y,suspend=n -jar /server/fapi-test-suite.jar
    links:
     - mongodb:mongodb
    depends_on: 
     - mongodb
    

