version: '3'
services:
  builder:
    image: gliderlabs/herokuish
    volumes:
     - ${MAVEN_CACHE}:/tmp/cache/.m2
     - .:/tmp/app:ro
     - ./target:/target
    command: /bin/bash -c '/bin/herokuish buildpack build && cp -v /app/target/*.jar /target'
  mongodb:
    image: mongo
    volumes:
     - ./mongo/data:/data/db
  server:
    image: openjdk
    ports:
     - "8080:8080"
    # Add this port for debugging
    # - "9999:9999"
    volumes:
     - ./target/:/server/
    command: java -jar /server/fapi-test-suite.jar
    # Use this one for remote debugging instead
    #command: java -Xdebug -Xrunjdwp:transport=dt_socket,address=9999,server=y,suspend=n -jar /server/fapi-test-suite.jar
    links:
     - mongodb:mongodb
    depends_on: 
     - mongodb
    

