apiVersion: v1
kind: Service
metadata:
  name: {{ template "microauthname" . }}
  labels:
    app: {{ template "microauthname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: microauth
  selector:
    app: {{ template "microauthname" . }}
