apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "microauthname" . }}
  labels:
    app: {{ template "microauthname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "microauthname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
    spec:
      containers:
      - name: microauth
        image: "{{ .Values.image.repository }}:microauth-{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: client_id
          valueFrom:
            secretKeyRef:
              name: microauth
              key: client_id
        - name: client_secret
          valueFrom:
            secretKeyRef:
              name: microauth
              key: client_secret
        - name: resource_id
          valueFrom:
            secretKeyRef:
              name: microauth
              key: resource_id
        - name: resource_secret
          valueFrom:
            secretKeyRef:
              name: microauth
              key: resource_secret
        ports:
        - containerPort: 9001
